

GET http://127.0.0.1:3000/api/user HTTP/1.1
###
GET http://127.0.0.1:3000/api/user?page=5 HTTP/1.1
###
GET http://127.0.0.1:3000/api/user?sortBy=createdAt&orderBy=desc HTTP/1.1
###
GET http://127.0.0.1:3000/api/item HTTP/1.1
###
GET http://127.0.0.1:3000/api/item/40e2061f-520e-448f-a131-60018f88ffe0 HTTP/1.1
###

GET http://127.0.0.1:3000/api/user/bd757793-c6ca44b6-be8f-ec6230783b6a HTTP/1.1
Content-Type: application/json
###


POST http://127.0.0.1:3000/api/user HTTP/1.1
Content-Type: application/json

{
    "username": "penssssaaaaaaaa"
}

###
GET http://127.0.0.1:3000/api/item HTTP/1.1
Content-Type: application/json

###

POST http://127.0.0.1:3000/api/item HTTP/1.1
Content-Type: application/json

{
    "itemType": "Notes",
    "content": "aaaaaaaaaaaa dont delete me ",
    "creator": "72ae8f1d-643b-483f-874b-2d48d0041183"
}

###

PUT http://127.0.0.1:3000/api/user/95293fa4-0cf0-49e4-b5e1-830ffdb3f36c HTTP/1.1
Content-Type: application/json

{
  "_id": "bf48eba3-f1b3-4cf4-af15-1676aaa111e7",
  "username": "Parties",
  "perferences": {
      "lang": "eng",
      "perro": "long"
  },
  "__v": 0
}

###

PUT http://127.0.0.1:3000/api/item/40e2061f-520e-448f-a131-60018f88ffe0 HTTP/1.1
Content-Type: application/json

{
    "itemType": "Notes",
    "content": "A simple no  and magic",
    "creator": "72ae8f1d-643b-483f-874b-2d48d0041183",
    "__v": 0
}

###
DELETE http://127.0.0.1:3000/api/item/473dd7ae-a7b4-452e-8310-3c5c16142dd4 HTTP/1.1

###


DELETE http://127.0.0.1:3000/api/user/32ae3e4c-a3db-4c4b-aa3d-3582afbc82f9 HTTP/1.1